version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: job_scheduler_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: job_scheduler_db
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - job_scheduler_network

  redis:
    image: redis:7
    container_name: job_scheduler_redis
    ports:
      - "6379:6379"
    networks:
      - job_scheduler_network

volumes:
  postgres_data:

networks:
  job_scheduler_network:
    driver: bridge
