INSERT INTO public.jobs
(id, "name", description, "type", payload, retry_policy, timeout, created_at, updated_at)
VALUES(3, '🧾 Stock Summary News', 'Menyusun ringkasan berita-berita per saham dari hasil scraping, serta menganalisis potensi dampak berita terhadap pergerakan saham.', 'stock_news_summary', '{"max_news_each_stock": 8, "max_news_age_in_days": 2, "min_confidence_score": 0.6, "min_to_summarize_news": 2}'::jsonb, '{"max_retries": 0, "backoff_strategy": "string", "initial_interval": "string"}'::jsonb, 1800, '2025-06-17 07:36:03.828', '2025-06-17 07:36:03.828');
INSERT INTO public.jobs
(id, "name", description, "type", payload, retry_policy, timeout, created_at, updated_at)
VALUES(7, '📈 Stock Position Monitoring', 'Menganalisis posisi saham pengguna secara berkala dan memberikan notifikasi jika diperlukan tindakan, seperti take profit, cut loss, atau menyesuaikan stop loss.', 'stock_position_monitor', '{"range": "14d", "interval": "1h", "send_notif": true}'::jsonb, '{"max_retries": 0, "backoff_strategy": "string", "initial_interval": "string"}'::jsonb, 60, '2025-06-24 13:16:48.057', '2025-06-24 13:16:48.057');
INSERT INTO public.jobs
(id, "name", description, "type", payload, retry_policy, timeout, created_at, updated_at)
VALUES(4, '🚨 Stock Price Alert', 'Mengirim peringatan ke Telegram saat harga saham mencapai batas yang telah ditentukan (TP/SL).
', 'stock_price_alert', '{"data_range": "1d", "data_interval": "1m", "alert_cache_duration": "30m", "alert_trigger_window_duration": "5m", "alert_resend_threshold_percent": 2.0}'::jsonb, '{"max_retries": 0, "backoff_strategy": "string", "initial_interval": "string"}'::jsonb, 50, '2025-06-17 20:44:35.326', '2025-06-17 20:44:35.326');
INSERT INTO public.jobs
(id, "name", description, "type", payload, retry_policy, timeout, created_at, updated_at)
VALUES(5, '📊 Stock Analyze', 'Menganalisis saham-saham dalam whitelist sistem untuk menghasilkan sinyal beli atau jual secara otomatis. Hasil analisis ini juga digunakan dalam fitur /buylist.', 'stock_analyzer', '{"skip_stocks": [], "use_stock_list": false, "use_trading_view": true, "additional_stocks": [], "trading_view_data": {"sort": {"sortBy": "Recommend.All", "sortOrder": "desc"}, "range": [0, 50], "filter": [{"left": "market_cap_basic", "right": 10000000000000, "operation": "egreater"}, {"left": "average_volume_10d_calc", "right": 10000000, "operation": "greater"}, {"left": "is_primary", "right": true, "operation": "equal"}], "columns": ["Recommend.All"], "markets": ["indonesia"], "options": {"lang": "en"}, "symbols": {}, "ignore_unknown_fields": false}}'::jsonb, '{"max_retries": 0, "backoff_strategy": "string", "initial_interval": "string"}'::jsonb, 60, '2025-06-23 16:57:18.359', '2025-06-23 16:57:18.359');
INSERT INTO public.jobs
(id, "name", description, "type", payload, retry_policy, timeout, created_at, updated_at)
VALUES(1, '📰 Stock News Scraper', 'Mengambil berita saham terbaru menggunakan Google RSS, lalu menganalisis dan merangkum kontennya dengan Gemini AI.', 'stock_news_scraper', '{"max_news": 5, "delay_interval": 1, "max_concurrent": 10, "use_stock_list": false, "source_priority": {"https://investor.id": 4, "https://www.bisnis.com": 3, "https://id.investing.com": 2, "https://www.kontan.co.id": 5, "https://finance.detik.com": 7, "https://www.idxchannel.com": 6, "https://www.cnbcindonesia.com": 1}, "use_stock_position": true, "additional_keywords": ["/search?q=investasi+saham", "/search?q=dampak+saham", "/search?q=saham+naik", "/search?q=saham+turun", "/search?q=IHSG"], "blacklisted_domains": ["padek.jawapos.com", "www.msn.com", "dataindonesia.id", "id.investing.com", "www.neraca.co.id", "tirto.id"], "max_news_age_in_days": 2, "additional_stock_codes": []}'::jsonb, '{"max_retries": 0, "backoff_strategy": "string", "initial_interval": "string"}'::jsonb, 1800, '2025-06-17 06:51:27.896', '2025-06-17 06:51:27.896');