INSERT INTO stocks (code, name, created_at, updated_at) VALUES
('ACES', 'Aspirasi Hidup Indonesia Tbk.', NOW(), NOW()),
('ADMR', 'Adaro Minerals Indonesia Tbk.', NOW(), NOW()),
('ADRO', 'Alamtri Resources Indonesia Tbk.', NOW(), NOW()),
('AKRA', 'AKR Corporindo Tbk.', NOW(), NOW()),
('AMMN', 'Amman Mineral Internasional Tbk.', NOW(), NOW()),
('AMRT', 'Sumber Alfaria Trijaya Tbk.', NOW(), NOW()),
('ANTM', 'Aneka Tambang Tbk.', NOW(), NOW()),
('ARTO', 'Bank Jago Tbk.', NOW(), NOW()),
('ASII', 'Astra International Tbk.', NOW(), NOW()),
('BBCA', 'Bank Central Asia Tbk.', NOW(), NOW()),
('BBNI', 'Bank Negara Indonesia (Persero) Tbk.', NOW(), NOW()),
('BBRI', 'Bank Rakyat Indonesia (Persero) Tbk.', NOW(), NOW()),
('BBTN', 'Bank Tabungan Negara (Persero) Tbk.', NOW(), NOW()),
('BMRI', 'Bank Mandiri (Persero) Tbk.', NOW(), NOW()),
('BRIS', 'Bank Syariah Indonesia Tbk.', NOW(), NOW()),
('BRPT', 'Barito Pacific Tbk.', NOW(), NOW()),
('CPIN', 'Charoen Pokphand Indonesia Tbk.', NOW(), NOW()),
('CTRA', 'Ciputra Development Tbk.', NOW(), NOW()),
('ESSA', 'Surya Esa Perkasa Tbk.', NOW(), NOW()),
('EXCL', 'XL Axiata Tbk.', NOW(), NOW()),
('GOTO', 'GoTo Gojek Tokopedia Tbk.', NOW(), NOW()),
('ICBP', 'Indofood CBP Sukses Makmur Tbk.', NOW(), NOW()),
('INCO', 'Vale Indonesia Tbk.', NOW(), NOW()),
('INDF', 'Indofood Sukses Makmur Tbk.', NOW(), NOW()),
('INKP', 'Indah Kiat Pulp & Paper Tbk.', NOW(), NOW()),
('ISAT', 'Indosat Tbk.', NOW(), NOW()),
('ITMG', 'Indo Tambangraya Megah Tbk.', NOW(), NOW()),
('JPFA', 'Japfa Comfeed Indonesia Tbk.', NOW(), NOW()),
('JSMR', 'Jasa Marga (Persero) Tbk.', NOW(), NOW()),
('KLBF', 'Kalbe Farma Tbk.', NOW(), NOW()),
('MAPA', 'MAP Aktif Adiperkasa Tbk.', NOW(), NOW()),
('MAPI', 'Mitra Adiperkasa Tbk.', NOW(), NOW()),
('MBMA', 'Merdeka Battery Materials Tbk.', NOW(), NOW()),
('MDKA', 'Merdeka Copper Gold Tbk.', NOW(), NOW()),
('MEDC', 'Medco Energi Internasional Tbk.', NOW(), NOW()),
('PGAS', 'Perusahaan Gas Negara Tbk.', NOW(), NOW()),
('PGEO', 'Pertamina Geothermal Energy Tbk.', NOW(), NOW()),
('PTBA', 'Bukit Asam Tbk.', NOW(), NOW()),
('SIDO', 'Industri Jamu dan Farmasi Sido Muncul Tbk.', NOW(), NOW()),
('SMGR', 'Semen Indonesia Tbk.', NOW(), NOW()),
('SMRA', 'Summarecon Agung Tbk.', NOW(), NOW()),
('TLKM', 'Telkom Indonesia Tbk.', NOW(), NOW()),
('TOWR', 'Sarana Menara Nusantara Tbk.', NOW(), NOW()),
('UNTR', 'United Tractors Tbk.', NOW(), NOW()),
('UNVR', 'Unilever Indonesia Tbk.', NOW(), NOW());