app:
  name: "golang-stock-scryper-executor"

database:
  host: "localhost" # For local development, use 'postgres' for docker-compose
  port: 5434
  name: "job_scheduler_db"
  user: "postgres"
  password: "password"
  ssl_mode: "disable"
  max_open_conns: 25
  max_idle_conns: 5
  conn_max_lifetime: "5m"

redis:
  host: "localhost" # For local development, use 'redis' for docker-compose
  port: 6379
  password: ""
  db: 0
  pool_size: 10

executor:
  max_concurrent_tasks: 10
  redis_stream_task_execution_timeout: "1m"
  redis_stream_stock_analyzer_timeout: "1m"
  redis_stream_stock_analyzer_retry_interval: "1m"
  redis_stream_stock_analyzer_max_idle_duration: "5m"
  redis_stream_stock_analyzer_max_retry: 3

  redis_stream_stock_position_monitor_timeout: "1m"
  redis_stream_stock_position_monitor_retry_interval: "30s"
  redis_stream_stock_position_monitor_max_idle_duration: "1m"
  redis_stream_stock_position_monitor_max_retry: 3
logger:
  level: "debug" # debug, info, warn, error, fatal, panic
  encoding: "json" # json, console

openrouter:
  api_key: "XXXXXX"
  model: "deepseek/deepseek-chat-v3-0324:free"

gemini:
  api_key: "XXXXX"
  model: "gemini-2.0-flash"
  max_request_per_minute: 15
  max_token_per_minute: 1_000_000
  base_url: "https://generativelanguage.googleapis.com/v1beta/models"

openai:
  api_key: "XXXXX"
  model: "gpt-4.1-nano"
  max_request_per_minute: 20
  max_token_per_minute: 1_000_000
  base_url: "https://api.openai.com/v1/chat/completions"


ai:
  provider: "gemini" # openrouter or gemini or openai

telegram:
  bot_token: "XXXXXXXX"
  chat_id: 123123

yahoo_finance:
  base_url: "https://query1.finance.yahoo.com/v8/finance/chart"
  max_request_per_minute: 15

tradingview:
  max_request_per_minute: 15
  base_url: "https://scanner.tradingview.com"
  payload_get_stock_buy_list: "{ \"columns\": [ \"Recommend.All\" ], \"filter\": [ { \"left\": \"market_cap_basic\", \"operation\": \"egreater\", \"right\": 10000000000000 }, { \"left\": \"average_volume_10d_calc\", \"operation\": \"greater\", \"right\": 10000000 }, { \"left\": \"is_primary\", \"operation\": \"equal\", \"right\": true } ], \"ignore_unknown_fields\": false, \"options\": { \"lang\": \"en\" }, \"range\": [ 0, 20 ], \"sort\": { \"sortBy\": \"Recommend.All\", \"sortOrder\": \"desc\" }, \"symbols\": {}, \"markets\": [ \"indonesia\" ] }"
  buy_list_min_technical_rating: 0.45